-- select * from FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_JUDE_SEBASTIAN;

SELECT TOTAL_RECOVERED, TOTAL_ACTIVE_CASES,TOTAL_DEATHS, DATE, COUNTRY FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_JUDE_SEBASTIAN