SELECT PROVINCE,
SUM(NEW_CASES) AS NEW_CASES,
SUM(NEW_DEATHS) AS NEW_DEATHS,
SUM(NEW_RECOVERED) AS NEW_RECOVERED,
AVG(GROWTH_FACTOR_OF_NEW_CASES) AS GROWTH_FACTOR_OF_NEW_CASES,
AVG(GROWTH_FACTOR_OF_NEW_DEATHS) AS GROWTH_FACTOR_OF_NEW_DEATHS,
AVG(CASE_FATALITY_RATE) AS CASE_FATALITY_RATE,
AVG(CASE_RECOVERED_RATE) AS CASE_RECOVERED_RATE,
DATE
FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_JUDE_SEBASTIAN
WHERE PROVINCE IS NOT NULL
GROUP BY PROVINCE,DATE